### ISSUE TITLE
Story Dialogs as dots

### ISSUE THREAD

**Issue by kaizer1v** [kaizer1v/brown_uni#10]
Make the story dialogs as close-able circles that popup instead of the entire dialog with the text in it.

**Comment by sssl03** [comment]
They may appear as circles/dots on the screen, which a person clicks on to open the story (and then can close them too). They may also appear in some other manner. It may actually be enough to just have the text show up with a nice underline/link.

**Comment by kaizer1v** [comment]
removed dots, loading all associated stories into a dialog
